#
#  Podfile
#  RNSwiftAppDemo
#
#  Created by Lyice Lee on 2017/07/14.
#  Copyright © 2017年 Facebook. All rights reserved.
#

target 'RNSwiftAppDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNSwiftAppDemo
  pod 'React', :path => './../node_modules/react-native', :subspecs => [
    'Core',
    'RCTWebSocket',
    # ...add modules name
  ]

  pod "Yoga", :path => "./../node_modules/react-native/ReactCommon/yoga"

  # ...add package name

end